name: workerTests
run-name: ${{ github.actor }} is testing worker
on: [push]
jobs:
  run-worker-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: |
          npm install
          npm run build --if-present
          npm run test --if-present
